cd C:/Prog/ExtLib/cmake-seqan3-unit-build-debug
set /p DUMMY=Hit ENTER to continue...

C:\MinGW\bin\mingw32-make.exe gtest_project
set /p DUMMY=Hit ENTER to continue...

rem C:\MinGW\bin\mingw32-make.exe gbenchmark_project
set /p DUMMY=Hit ENTER to continue...

C:\MinGW\bin\mingw32-make.exe -k
set /p DUMMY=Hit ENTER to continue...

"C:\Program Files\CMake\bin\ctest.exe" . --output-on-failure
set /p DUMMY=Hit ENTER to continue...
